global:
  imageRegistry: apptrustswampupc.jfrog.io
platform:
  version: 2.1.29
platformWebhook: {}
web:
  repository: apptrustswampupc.jfrog.io/bookverse-web-internal-docker-release-local/web
  tag: 1.6.14  # Updated to include entrypoint.sh fix for env var substitution
  replicas: 1
  port: 8080
  env:
    BOOKVERSE_ENV: DEV
    # Backend service URLs - use internal k8s service names for production
    # For local development with port-forwarding, use localhost URLs
    INVENTORY_BASE_URL: http://inventory
    RECOMMENDATIONS_BASE_URL: http://recommendations
    CHECKOUT_BASE_URL: http://checkout
  ingress:
    enabled: false
    className: ''
    host: ''
    annotations: {}
    tls:
      enabled: false
      secretName: ''
  service:
    type: ClusterIP
inventory:
  repository: apptrustswampupc.jfrog.io/bookverse-inventory-internal-docker-release-local/inventory
  tag: 1.5.11
  replicas: 1
  port: 8000
recommendations:
  repository: apptrustswampupc.jfrog.io/bookverse-recommendations-internal-docker-release-local/recommendations
  tag: 2.7.14
  replicas: 1
  port: 8000
  env:
    INVENTORY_BASE_URL: http://inventory
  cache:
    ttlSeconds: 60
  worker:
    enabled: true
    repository: apptrustswampupc.jfrog.io/bookverse-recommendations-internal-docker-release-local/recommendations-worker
    tag: 1.8.22
    replicas: 1
    refreshSeconds: 60
  config:
    enabled: true
    mountPath: /app/config
    data:
      recommendations-settings.yaml: "weights:\n  genre: 1.0\n  author: 0.25\n  popularity:\
        \ 0.10\nlimits:\n  default: 10\n  max: 50\nfeatures:\n  filter_out_of_stock:\
        \ true\n  enable_cache: false\n  ttl_seconds: 60\n"
  resources:
    enabled: true
    mountPath: /app/resources
    data:
      stopwords.txt: 'the

        and

        of

        to

        a

        '
checkout:
  repository: apptrustswampupc.jfrog.io/bookverse-checkout-internal-docker-release-local/checkout
  tag: 3.2.15
  replicas: 1
  port: 8000
  env:
    INVENTORY_BASE_URL: http://inventory
    REQUEST_TIMEOUT_SECONDS: '2'
    RETRY_ATTEMPTS: '2'
    PAYMENT_SUCCESS_RATIO: '1.0'
    LOG_LEVEL: INFO
