global:
  imageRegistry: "${DOCKER_REGISTRY}"

web:
  repository: "${DOCKER_REGISTRY}/${PROJECT_KEY}-web-docker-internal-local/web"
  tag: "dev"
  env:
    BOOKVERSE_ENV: "DEV"
    INVENTORY_BASE_URL: "http://inventory"
    RECOMMENDATIONS_BASE_URL: "http://recommendations"
    CHECKOUT_BASE_URL: "http://checkout"

inventory:
  repository: "${DOCKER_REGISTRY}/${PROJECT_KEY}-inventory-docker-internal-local/inventory"
  tag: "dev"

recommendations:
  repository: "${DOCKER_REGISTRY}/${PROJECT_KEY}-recommendations-docker-internal-local/recommendations"
  tag: "dev"

checkout:
  repository: "${DOCKER_REGISTRY}/${PROJECT_KEY}-checkout-docker-internal-local/checkout"
  tag: "dev"

