apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: {{ default "" .Values.inventory.repository }}:{{ default "latest" .Values.inventory.tag }}
          ports:
            - containerPort: {{ .Values.inventory.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.inventory.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.inventory.port }}
            initialDelaySeconds: 15
            periodSeconds: 20

