apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-web
spec:
  replicas: {{ default 1 .Values.web.replicas }}
  selector:
    matchLabels:
      app: platform-web
  template:
    metadata:
      labels:
        app: platform-web
    spec:
      containers:
        - name: web
          image: {{ printf "%s:%s" (default "" .Values.web.repository) (required "web.tag is required" .Values.web.tag) }}
          ports:
            - containerPort: {{ .Values.web.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.web.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.web.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: BOOKVERSE_ENV
              value: {{ quote .Values.web.env.BOOKVERSE_ENV }}
            - name: INVENTORY_BASE_URL
              value: {{ quote .Values.web.env.INVENTORY_BASE_URL }}
            - name: RECOMMENDATIONS_BASE_URL
              value: {{ quote .Values.web.env.RECOMMENDATIONS_BASE_URL }}
            - name: CHECKOUT_BASE_URL
              value: {{ quote .Values.web.env.CHECKOUT_BASE_URL }}

