apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-web
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: platform-web
                port:
                  number: 80

