{{- if and .Values.platformWebhook.enabled .Values.platformWebhook.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-webhook
  {{- if .Values.platformWebhook.ingress.annotations }}
  annotations:
  {{- range $k, $v := .Values.platformWebhook.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
spec:
  {{- if .Values.platformWebhook.ingress.className }}
  ingressClassName: {{ .Values.platformWebhook.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.platformWebhook.ingress.host }}
      http:
        paths:
          - path: /webhooks/apptrust
            pathType: Prefix
            backend:
              service:
                name: platform-webhook
                port:
                  number: 80
  {{- if .Values.platformWebhook.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.platformWebhook.ingress.tls.secretName }}
      hosts:
        - {{ .Values.platformWebhook.ingress.host }}
  {{- end }}
{{- end }}


