{{- if .Values.web.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-web
  {{- if and .Values.web.ingress.annotations (gt (len .Values.web.ingress.annotations) 0) }}
  annotations:
{{ toYaml .Values.web.ingress.annotations | indent 4 }}
  {{- end }}
spec:
  {{- if .Values.web.ingress.className }}
  ingressClassName: {{ .Values.web.ingress.className }}
  {{- end }}
  {{- if and .Values.web.ingress.tls.enabled .Values.web.ingress.host }}
  tls:
    - secretName: {{ .Values.web.ingress.tls.secretName }}
      hosts:
        - {{ .Values.web.ingress.host | quote }}
  {{- else if .Values.web.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.web.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.web.ingress.host | default "" | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: platform-web
                port:
                  number: 80
{{- end }}

