apiVersion: v1
kind: Service
metadata:
  name: platform-web
spec:
  type: ClusterIP
  selector:
    app: platform-web
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.web.port }}

