apiVersion: v1
kind: Service
metadata:
  name: recommendations
spec:
  type: ClusterIP
  selector:
    app: recommendations
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.recommendations.port }}

