name: On Platform Release

on:
  repository_dispatch:
    types: [platform_release]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Platform tag to process'
        required: false
        type: string
      DEMO_MODE:
        description: 'Enable demo mode (verbose logs, request tracing)'
        required: false
        default: 'false'
        type: choice
        options: ['false', 'true']

jobs:
  handle-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Apply DEMO_MODE settings
        if: ${{ inputs.DEMO_MODE == 'true' || env.DEMO_MODE == 'true' }}
        run: |
          echo "🔔 DEMO_MODE enabled"
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
          echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
          echo "HTTP_DEBUG_LEVEL=verbose" >> $GITHUB_ENV
          echo "BASH_XTRACE_ENABLED=1" >> $GITHUB_ENV

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Read payload
        id: payload
        run: |
          echo "Tag from payload: ${{ github.event.client_payload.tag }}"
          echo "tag=${{ github.event.client_payload.tag }}" >> $GITHUB_OUTPUT

      - name: Bump chart version (placeholder)
        run: |
          echo "(placeholder) Bump charts/platform/Chart.yaml version based on ${{ steps.payload.outputs.tag }}"

      - name: Commit changes (placeholder)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add charts/platform || true
          git commit -m "chore(platform): update chart on platform release ${{ steps.payload.outputs.tag }}" || true
          git push


